name: suzuki_code_picker
description: A flutter package for showing a marken selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox
version: 1.3.15


environment:
  sdk: ">=2.2.2  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - logos/
    - lib/i18n/en.json
    - lib/i18n/it.json
    - lib/i18n/fr.json
    - lib/i18n/es.json
    - lib/i18n/de.json
