name: Publish plugin

on:
  push:
    tags: 
      - v*

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.2.1
        with:
          credential: ${{ secrets.CREDENTIALS }}
          skip_test: true
