/// Flutter icons MyMotoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyMotoIcons
///      fonts:
///       - asset: fonts/MyMotoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyMotoIcons {
  MyMotoIcons._();

  static const _kFontFam = 'MyMotoIcons';
  static const _kFontPkg = null;

  static const IconData statsdick = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statsduenn = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationdick = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pfeilrechts = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pfeillinks = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meinmotorrad = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationduenn = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meinmotorradneu = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData einstellungen = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kostenduenn = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmdick = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmduenn = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kostendick = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
